### PR TITLE
Reformat LICENSE

### PR DESCRIPTION
**Pull request by hadisfr**
Reformat [LICENSE.md](LICENSE.md) to make it recognized by GitHub

### CODE REVIEW

**Comment by facelessuser** [comment]
I've restarting failing tests as they seemed to stop before tests even started.  Travis has been real hit or miss these last couple of days...

**Comment by facelessuser** [comment]
On an aside, can you elaborate on what you mean by make GitHub recognize the license?

**Comment by hadisfr** [comment]
Nothing so important thing. Just showing MIT badge in the top bar of project (next to contributors, releases, etc) and showing a summery of MIT License properties when someone is looking at [LICENSE.md]([LICENSE.md]) at GitHub.

**Comment by hadisfr** [comment]
Travis connection to Amazon AWS SSL has been timed out. It's so strange….

**Comment by facelessuser** [comment]
Cool.  I post the license at the top of the readme, but I'm okay with this as well 🙂 . I'll merge once Travis CI stops being difficult.

**Pull request merged**
